### ISSUE TITLE
Zombie Enchantsmith has no texture

### ISSUE THREAD

**Issue by WerDei** [Scouter456/Enchantsmith#1]
Zombie villager of Enchantsmith profession has a placeholder texture
Tested on Fabric 1.12.1
Mods: Fabric API, Enchantsmith

![2024-02-10_13 12 32](https://github.com/Scouter456/Enchantsmith/assets/48105614/8f6a3c66-c979-4ce0-b05c-30844e6374b3)

**Comment by Scouter456** [comment]
Is fixed in the latest version
