### ISSUE TITLE
[Crash] crash when trading with enchantsmith 

### ISSUE THREAD

**Issue by memphismc** [Scouter456/Enchantsmith#2]
[crash-2024-03-04_22.18.33-client.txt](https://github.com/Scouter456/Enchantsmith/files/14486744/crash-2024-03-04_22.18.33-client.txt)

**Comment by Scouter456** [comment]
Should be fixed in the latest version

**Comment by memphismc** [comment]
> Should be fixed in the latest version

just out of curiosity, i have other mods that add enchantments so should i keep using enchantsmith or do you think ill keep encountering crashes like these for the other enchantment mods? if so i can drop enchantsmith for good, or it might just have been a serious issue on spellbound's part and im not aware, i dont know, make it clear for me if you can please

**Comment by Scouter456** [comment]
This was more of a small thing where the spellbound was expecting a player for a method where player could be null but they didnt have a null check (for getting the tooltip of the itemstack). I added a player for it now so it shouldnt happen anymore. For the rest if the mods just add enchantments normally there should be no issue as enchantsmith doesnt change any enchants
